name: Generate the release plugin

# How to start the Github Action
on: pull_request

env:
  NAME_PACKAGE: unreal-moderlab-pipeline.zip
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

# Execute this command
jobs:
  package:
    name: Make Unreal Package
    runs-on: ubuntu-18.04
    steps:
      # On the runner, get the repository
      - name: Get the repository
        uses: actions/checkout@main

      # Make an archive with the plugin source only
      - name: Create zip archive release
        run: |
          cd '${{ github.workspace }}/unreal-pipeline'
          zip -r '${{ github.workspace }}/Releases/${{env.NAME_PACKAGE}}' * -x '.git*' 'Releases/.keep'

      # Prepare the setup with a Pull Request
      - name: Set a release package
        id: release
        if: ${{ contains(github.head_ref, 'develop') }}
        uses: rymndhng/release-on-push-action@master
        with:
          bump_version_scheme: patch

      # Attach the previous archive to the last release
      - name: Push release
        uses: svenstaro/upload-release-action@v2
        if: ${{ contains(github.head_ref, 'develop') }}
        with:
          file: './releases/${{env.NAME_PACKAGE}}'
          asset_name: '${{env.NAME_PACKAGE}}'
          tag: ${{ steps.release.outputs.tag_name }}
          repo_token: ${{secrets.GITHUB_TOKEN}}
          overwrite: true